"""Initial migration

Revision ID: 17a7edcac291
Revises: 
Create Date: 2025-07-26 12:55:16.629419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a7edcac291'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False, comment='规则编码'),
    sa.Column('rule_name', sa.String(length=200), nullable=False, comment='规则名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='规则描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='规则类别'),
    sa.Column('subcategory', sa.String(length=50), nullable=True, comment='子类别'),
    sa.Column('applicable_stage', sa.String(length=20), nullable=True, comment='适用阶段'),
    sa.Column('rule_content', sa.Text(), nullable=False, comment='规则内容'),
    sa.Column('check_pattern', sa.Text(), nullable=True, comment='检查模式(正则表达式或关键词)'),
    sa.Column('severity', sa.String(length=10), nullable=True, comment='严重程度：low/medium/high/critical'),
    sa.Column('legal_basis', sa.Text(), nullable=True, comment='法律依据'),
    sa.Column('reference_documents', sa.Text(), nullable=True, comment='参考文件'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_automated', sa.Boolean(), nullable=True, comment='是否支持自动检查'),
    sa.Column('version', sa.String(length=20), nullable=True, comment='版本号'),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True, comment='生效日期'),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True, comment='失效日期'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_index(op.f('ix_compliance_rules_id'), 'compliance_rules', ['id'], unique=False)
    op.create_table('review_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='阶段名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='阶段描述'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='阶段顺序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_stages_id'), 'review_stages', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('permissions', sa.Text(), nullable=False, comment='权限列表(JSON格式)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统角色'),
    sa.Column('parent_role_id', sa.Integer(), nullable=True, comment='父角色ID'),
    sa.Column('level', sa.Integer(), nullable=True, comment='角色层级'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('review_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='要点编码'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='要点标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='要点描述'),
    sa.Column('review_type', sa.String(length=20), nullable=False, comment='审查类型：manual/auto/both'),
    sa.Column('is_required', sa.Boolean(), nullable=True, comment='是否必审'),
    sa.Column('risk_level', sa.String(length=10), nullable=True, comment='风险等级：low/medium/high'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='要点顺序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('review_criteria', sa.Text(), nullable=True, comment='审查标准'),
    sa.Column('legal_basis', sa.Text(), nullable=True, comment='法律依据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['review_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_review_points_id'), 'review_points', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='姓名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('employee_id', sa.String(length=50), nullable=True, comment='工号'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='职位'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='电话'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级用户'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否已验证'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色ID'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='额外权限(JSON格式)'),
    sa.Column('reviewer_level', sa.String(length=20), nullable=True, comment='审查员级别：junior/senior/expert/chief'),
    sa.Column('specialties', sa.Text(), nullable=True, comment='专业领域(JSON格式)'),
    sa.Column('certification', sa.String(length=100), nullable=True, comment='资质证书'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('login_count', sa.Integer(), nullable=True, comment='登录次数'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True, comment='失败登录次数'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='锁定到期时间'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='密码修改时间'),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True, comment='密码重置令牌'),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True, comment='重置令牌过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=50), nullable=True, comment='资源ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='操作描述'),
    sa.Column('old_values', sa.Text(), nullable=True, comment='修改前的值(JSON格式)'),
    sa.Column('new_values', sa.Text(), nullable=True, comment='修改后的值(JSON格式)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='请求ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='操作状态：success/failure/error'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False, comment='项目编号'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('project_type', sa.String(length=50), nullable=False, comment='项目类型：货物/工程/服务'),
    sa.Column('procurement_method', sa.String(length=50), nullable=True, comment='采购方式：公开招标/邀请招标/竞争性谈判/单一来源/询价'),
    sa.Column('budget_source', sa.String(length=100), nullable=True, comment='资金来源'),
    sa.Column('budget_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='预算金额'),
    sa.Column('contract_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='合同金额'),
    sa.Column('final_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='最终金额'),
    sa.Column('planned_start_date', sa.Date(), nullable=True, comment='计划开始日期'),
    sa.Column('planned_end_date', sa.Date(), nullable=True, comment='计划结束日期'),
    sa.Column('actual_start_date', sa.Date(), nullable=True, comment='实际开始日期'),
    sa.Column('actual_end_date', sa.Date(), nullable=True, comment='实际结束日期'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='项目状态：planning/procurement/implementation/acceptance/completed/cancelled'),
    sa.Column('review_status', sa.String(length=20), nullable=True, comment='审查状态：pending/in_progress/completed/rejected'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('procuring_entity', sa.String(length=200), nullable=True, comment='采购人'),
    sa.Column('procurement_agency', sa.String(length=200), nullable=True, comment='采购代理机构'),
    sa.Column('winning_bidder', sa.String(length=200), nullable=True, comment='中标人'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='项目负责人'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='所属部门'),
    sa.Column('priority', sa.String(length=10), nullable=True, comment='优先级：low/normal/high/urgent'),
    sa.Column('review_required', sa.Boolean(), nullable=True, comment='是否需要审查'),
    sa.Column('current_review_stage', sa.String(length=20), nullable=True, comment='当前审查阶段'),
    sa.Column('review_progress', sa.Integer(), nullable=True, comment='审查进度(百分比)'),
    sa.Column('risk_level', sa.String(length=10), nullable=True, comment='风险等级：low/medium/high/critical'),
    sa.Column('risk_factors', sa.Text(), nullable=True, comment='风险因素'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签(JSON格式)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False, comment='会话令牌'),
    sa.Column('refresh_token', sa.String(length=255), nullable=True, comment='刷新令牌'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活跃'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('device_info', sa.Text(), nullable=True, comment='设备信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(字节)'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('document_category', sa.String(length=50), nullable=False, comment='文档类别'),
    sa.Column('document_type', sa.String(length=100), nullable=True, comment='具体文档类型'),
    sa.Column('review_stage', sa.String(length=20), nullable=True, comment='所属审查阶段'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：uploaded/processing/processed/error'),
    sa.Column('is_processed', sa.Boolean(), nullable=True, comment='是否已处理'),
    sa.Column('is_ocr_processed', sa.Boolean(), nullable=True, comment='是否已OCR处理'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='提取的文本内容'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='OCR识别的文本'),
    sa.Column('ocr_engine', sa.String(length=20), nullable=True, comment='使用的OCR引擎：tesseract/paddleocr/trocr'),
    sa.Column('ocr_confidence', sa.Integer(), nullable=True, comment='OCR识别置信度(0-100)'),
    sa.Column('is_handwritten', sa.Boolean(), nullable=True, comment='是否包含手写内容'),
    sa.Column('ocr_details', sa.Text(), nullable=True, comment='OCR详细信息(JSON格式)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='文档摘要'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='关键词(JSON格式)'),
    sa.Column('version', sa.String(length=20), nullable=True, comment='版本号'),
    sa.Column('parent_document_id', sa.Integer(), nullable=True, comment='父文档ID'),
    sa.Column('review_priority', sa.String(length=10), nullable=True, comment='审查优先级：low/normal/high/urgent'),
    sa.Column('compliance_status', sa.String(length=20), nullable=True, comment='合规状态：compliant/non_compliant/pending'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='处理完成时间'),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('issue_code', sa.String(length=50), nullable=False, comment='问题编号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='问题标题'),
    sa.Column('description', sa.Text(), nullable=False, comment='问题描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='问题类别'),
    sa.Column('subcategory', sa.String(length=50), nullable=True, comment='问题子类别'),
    sa.Column('severity', sa.String(length=10), nullable=True, comment='严重程度：low/medium/high/critical'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：open/in_progress/resolved/closed/rejected'),
    sa.Column('priority', sa.String(length=10), nullable=True, comment='优先级：low/normal/high/urgent'),
    sa.Column('reporter_id', sa.Integer(), nullable=False, comment='报告人'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='负责人'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='截止日期'),
    sa.Column('resolution', sa.Text(), nullable=True, comment='解决方案'),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True, comment='解决日期'),
    sa.Column('verification_result', sa.Text(), nullable=True, comment='验证结果'),
    sa.Column('impact_assessment', sa.Text(), nullable=True, comment='影响评估'),
    sa.Column('cost_impact', sa.Numeric(precision=15, scale=2), nullable=True, comment='成本影响'),
    sa.Column('schedule_impact', sa.Integer(), nullable=True, comment='进度影响(天数)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='解决时间'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_code')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_table('project_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('compared_project_id', sa.Integer(), nullable=False),
    sa.Column('comparison_type', sa.String(length=50), nullable=False, comment='比对类型'),
    sa.Column('comparison_criteria', sa.Text(), nullable=True, comment='比对标准'),
    sa.Column('similarity_score', sa.Integer(), nullable=True, comment='相似度分数(0-100)'),
    sa.Column('differences', sa.Text(), nullable=True, comment='差异分析'),
    sa.Column('anomalies', sa.Text(), nullable=True, comment='异常发现'),
    sa.Column('risk_indicators', sa.Text(), nullable=True, comment='风险指标'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending/completed/reviewed'),
    sa.Column('analyst_id', sa.Integer(), nullable=True, comment='分析人员'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['compared_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_comparisons_id'), 'project_comparisons', ['id'], unique=False)
    op.create_table('project_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True, comment='审查状态：pending/in_progress/completed/rejected'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('total_points', sa.Integer(), nullable=True, comment='总要点数'),
    sa.Column('completed_points', sa.Integer(), nullable=True, comment='已完成要点数'),
    sa.Column('passed_points', sa.Integer(), nullable=True, comment='通过要点数'),
    sa.Column('failed_points', sa.Integer(), nullable=True, comment='未通过要点数'),
    sa.Column('review_opinion', sa.Text(), nullable=True, comment='审查意见'),
    sa.Column('conclusion', sa.String(length=20), nullable=True, comment='审查结论：pass/fail/conditional_pass'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['review_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_reviews_id'), 'project_reviews', ['id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('check_result', sa.String(length=20), nullable=False, comment='检查结果：pass/fail/warning/error'),
    sa.Column('confidence_score', sa.Integer(), nullable=True, comment='置信度分数(0-100)'),
    sa.Column('matched_content', sa.Text(), nullable=True, comment='匹配的内容'),
    sa.Column('violation_details', sa.Text(), nullable=True, comment='违规详情'),
    sa.Column('suggestions', sa.Text(), nullable=True, comment='改进建议'),
    sa.Column('check_method', sa.String(length=50), nullable=True, comment='检查方法：auto/manual/hybrid'),
    sa.Column('checker_id', sa.Integer(), nullable=True, comment='检查人员ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_id'), 'compliance_checks', ['id'], unique=False)
    op.create_table('document_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sa.Integer(), nullable=False),
    sa.Column('annotation_type', sa.String(length=50), nullable=False, comment='标注类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='标注内容'),
    sa.Column('position', sa.Text(), nullable=True, comment='标注位置(JSON格式)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/resolved/deleted'),
    sa.Column('importance', sa.String(length=10), nullable=True, comment='重要性：low/normal/high'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_annotations_id'), 'document_annotations', ['id'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型'),
    sa.Column('ocr_engine', sa.String(length=50), nullable=False, comment='OCR引擎'),
    sa.Column('language', sa.String(length=20), nullable=False, comment='识别语言'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='提取的文本内容'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='识别置信度'),
    sa.Column('processing_time', sa.Float(), nullable=True, comment='处理时间（秒）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('document_id', sa.Integer(), nullable=True, comment='关联文档ID'),
    sa.Column('processed_by', sa.Integer(), nullable=False, comment='处理者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_results_id'), 'ocr_results', ['id'], unique=False)
    op.create_table('review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_review_id', sa.Integer(), nullable=False),
    sa.Column('review_point_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False, comment='审查结果：pass/fail/na/pending'),
    sa.Column('score', sa.Integer(), nullable=True, comment='评分'),
    sa.Column('findings', sa.Text(), nullable=True, comment='发现的问题'),
    sa.Column('evidence', sa.Text(), nullable=True, comment='证据材料'),
    sa.Column('recommendations', sa.Text(), nullable=True, comment='整改建议'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('rectification_status', sa.String(length=20), nullable=True, comment='整改状态：pending/in_progress/completed'),
    sa.Column('rectification_deadline', sa.DateTime(timezone=True), nullable=True, comment='整改期限'),
    sa.Column('rectification_result', sa.Text(), nullable=True, comment='整改结果'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_review_id'], ['project_reviews.id'], ),
    sa.ForeignKeyConstraint(['review_point_id'], ['review_points.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_results_id'), 'review_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_results_id'), table_name='review_results')
    op.drop_table('review_results')
    op.drop_index(op.f('ix_ocr_results_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_document_annotations_id'), table_name='document_annotations')
    op.drop_table('document_annotations')
    op.drop_index(op.f('ix_compliance_checks_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_project_reviews_id'), table_name='project_reviews')
    op.drop_table('project_reviews')
    op.drop_index(op.f('ix_project_comparisons_id'), table_name='project_comparisons')
    op.drop_table('project_comparisons')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_review_points_id'), table_name='review_points')
    op.drop_table('review_points')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_review_stages_id'), table_name='review_stages')
    op.drop_table('review_stages')
    op.drop_index(op.f('ix_compliance_rules_id'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
