"""Add OAuth2 client and authorization code tables

Revision ID: dc5bca58112f
Revises: add_vector_tables
Create Date: 2025-07-29 10:18:35.323966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5bca58112f'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_authorization_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False, comment='授权码'),
    sa.Column('client_id', sa.String(length=255), nullable=False, comment='客户端ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False, comment='重定向URI'),
    sa.Column('scopes', sa.JSON(), nullable=True, comment='授权范围'),
    sa.Column('is_used', sa.Boolean(), nullable=True, comment='是否已使用'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth2_authorization_codes_code'), 'oauth2_authorization_codes', ['code'], unique=True)
    op.create_index(op.f('ix_oauth2_authorization_codes_id'), 'oauth2_authorization_codes', ['id'], unique=False)
    op.create_table('oauth2_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False, comment='客户端ID'),
    sa.Column('client_secret', sa.String(length=255), nullable=False, comment='客户端密钥'),
    sa.Column('client_name', sa.String(length=255), nullable=False, comment='客户端名称'),
    sa.Column('client_description', sa.Text(), nullable=True, comment='客户端描述'),
    sa.Column('grant_types', sa.JSON(), nullable=True, comment='支持的授权类型'),
    sa.Column('response_types', sa.JSON(), nullable=True, comment='支持的响应类型'),
    sa.Column('redirect_uris', sa.JSON(), nullable=True, comment='重定向URI列表'),
    sa.Column('scopes', sa.JSON(), nullable=True, comment='客户端权限范围'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_confidential', sa.Boolean(), nullable=True, comment='是否为机密客户端'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth2_clients_client_id'), 'oauth2_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth2_clients_id'), 'oauth2_clients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth2_clients_id'), table_name='oauth2_clients')
    op.drop_index(op.f('ix_oauth2_clients_client_id'), table_name='oauth2_clients')
    op.drop_table('oauth2_clients')
    op.drop_index(op.f('ix_oauth2_authorization_codes_id'), table_name='oauth2_authorization_codes')
    op.drop_index(op.f('ix_oauth2_authorization_codes_code'), table_name='oauth2_authorization_codes')
    op.drop_table('oauth2_authorization_codes')
    # ### end Alembic commands ###
